FROM apache/airflow:2.6.3

USER root

# Update and clean up
RUN apt-get update -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Install pipenv
RUN pip install pipenv
RUN pip install --upgrade pipenv
RUN pip install --upgrade pip setuptools wheel

# Copy Pipfile and Pipfile.lock
COPY ../Pipfile ../Pipfile.lock /

# Install Python dependencies with pipenv
# RUN cd / && pipenv install --verbose


# Copy necessary files and directories
COPY ./airflow/airflow_home/dags /opt/airflow/dags
COPY ./airflow/entrypoint.sh /entrypoint.sh

#changing user to root to execute next command since it needs necessary permissions. then we change back to airflow
USER root

RUN chmod +x /entrypoint.sh

USER airflow

EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh"]



# #START
# # CMD ["airflow", "webserver"]
