FROM apache/airflow:2.6.3

USER root

# Update and clean up
RUN apt-get update -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Install pipenv
RUN pip install pipenv
RUN pip install --upgrade pipenv
RUN pip install --upgrade pip setuptools wheel

# Copy Pipfile and Pipfile.lock. Copying from root directory where docker-compose.yaml file is, so not using ..
COPY /Pipfile /Pipfile.lock /

# Install Python dependencies with pipenv
# RUN cd / && pipenv install --verbose


# Copy necessary files and directories
COPY ./app /app
COPY ./airflow/airflow_home/dags /opt/airflow/dags
COPY ./airflow/entrypoint.sh /entrypoint.sh

#already ran this locally in terminal
# RUN chmod +x /entrypoint.sh

#changing user to root to execute next command since it needs necessary permissions. then we change back to airflow
USER root

USER airflow

ENV AIRFLOW__CORE__SQL_ALCHEMY_CONN=""

EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh"]



# #START
# # CMD ["airflow", "webserver"]
